### ISSUE TITLE
Unable to get minimal SPI example to work

### ISSUE THREAD

**Issue by HikingDev** [binhollc/binho-python-package#13]
Hi,

i am able to get the SPI bus to work using the MissionControl as well as using CoolTerm.
Unfortunately the same cannot be said about using the Python library.

Everything works up to the transfer call.

The Traceback is as follows:

`  File "******\binho_test.py", line 153, in <module>
    rxData = binho.spi.transfer(txData, 4, chip_select=csPin, invert_chip_select=invertCS)
  File "C:\Python39\lib\site-packages\binho\interfaces\spiBus.py", line 200, in transfer
    response = self.api.writeToReadFrom(writeFlag, readFlag, numBytes, bytes(chunk))
  File "C:\Python39\lib\site-packages\binho\comms\drivers\spi.py", line 159, in writeToReadFrom
    raise DeviceError(f'Error Binho responded with {result}, not the expected "-SPI0 RXD ..."')
binho.errors.DeviceError: Error Binho responded with -NG, not the expected "-SPI0 RXD ..."`

Any help is welcome

**Comment by jmg5150** [comment]
Hi, Thanks for reaching out about this, and sorry to hear about the trouble you're running into.

Would you mind checking the device firmware version, and updating it if it's not already running the latest? You can check the firmware version using the `binho info` CLI command -- it will indicate if the version is the latest or not. If necessary, you can update to the latest version using the `binho dfu -l` CLI command. If you still run into trouble running the example, please let me know the firmware version on your device, the MissionControl version that you're using, and we'll get to the bottom of this ASAP, however I suspect the issue might be resolved with the firmware update.

**Comment by HikingDev** [comment]
Hi @jmg5150 , 
the firmware update indeed solved the issue.
Thank you for your quick support.
